env:
  node: true
  es6: true
  jest: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - '**/node_modules/.*'
  - '**/dist/.*'
  - '**/coverage/.*'
  - '*.json'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2023
  sourceType: module
  project:
    - './.github/linters/tsconfig.json'
    - './tsconfig.json'

extends:
  - plugin:github/recommended
  - plugin:jest/recommended
  - '@mscharley'
  - '@mscharley/eslint-config/node'

plugins:
  - jest

rules:
  'camelcase': 'off'
  'no-console': 'off'
  'eslint-comments/no-use': 'off'
  'eslint-comments/no-unused-disable': 'off'
  'filenames/match-regex': 'off'
  'i18n-text/no-en': 'off'
