name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: .tool-versions
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: codegen
        run: pnpm run codegen

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run ci-test

  # test-action:
  #   name: GitHub Actions Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v4

  #     - name: Test Local Action
  #       id: test-action
  #       uses: ./
  #       with:
  #         milliseconds: 1000

  #     - name: Print Output
  #       id: output
  #       run: echo "${{ steps.test-action.outputs.time }}"
